---
title: "Data Handyman"
author: "Todd Grabowsky"
site: bookdown::bookdown_site
documentclass: book
output:
  bookdown::gitbook: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Preface

People who write code are a generous bunch. I'm indebted to the countless hackers, bloggers and stackoverflow-ers who prolificly share their code and insights. The goal of this book is to hopefully pay some of those gifts forward (and selfishly, to set aside some time and space to reflect on and reinforce the many things I've learned over the years). 

I am a data scientist by trade^["Data Scientist" has become an umbrella term that encompasses many data-oriented professions. As a result, I've had the privilege of wearing lots of hats throughout my career thus far, hence "Data Handyman". Projects ranging from statistical analysis to software architecture, from web scraping to user interface design. There are [lots of flavors](https://www.oreilly.com/data/free/analyzing-the-analyzers.csp) of data scientists in the same way that there are lots of different types of handymen. Some specialize in plumbing, some in electrical, and some do a little bit of everything.] and my tool of choice tends to be the R statistical programming language. So many, if not most, of the examples in this book use R. There are lots of great software tools out there and it's worth exploring them as time permits, but I'm sticking with what I know. One quick aside about choosing tools -- I believe strongly in the idea of "the right tool for the job at hand". It's always good to think deeply about a problem before deciding on a solution. Remember the ["law of the instrument"](https://en.wikipedia.org/wiki/Law_of_the_instrument): "if all you have is a hammer, everything looks like a nail". R just happens to be a Swiss Army knife, so I feel good using it in a lot of different situations `r emo::ji("smile")`.


